apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: semamesh-node-agent
  namespace: semamesh-system
  labels:
    app: semamesh
spec:
  selector:
    matchLabels:
      app: semamesh
  template:
    metadata:
      labels:
        app: semamesh
    spec:
      # CRITICAL: hostNetwork allows the eBPF program to see the node's real traffic
#      hostNetwork: true
#      dnsPolicy: ClusterFirstWithHostNet

      # The Identity needed to read SemaPolicy/Quota CRDs
      serviceAccountName: sema-controller-sa

      containers:
        - name: semamesh-agent
          image: semamesh-agent:latest
          imagePullPolicy: IfNotPresent

          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN", "NET_ADMIN", "BPF"]

          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            # Configurations for our Go Waypoint Proxy
            - name: TARGET_LLM
              value: "http://mock-llm-service.default.svc.cluster.local:8080"
            - name: PORT
              value: "8080"
            - name: SEMA_DEFAULT_TOKEN_LIMIT
              value: "1000"
            - name: SLACK_WEBHOOK_URL # Optional: Set this to enable alerts
              value: ""

          volumeMounts:
            - name: cgroup
              mountPath: /sys/fs/cgroup
            - name: bpf-maps
              mountPath: /sys/fs/bpf

      volumes:
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
            type: Directory
        - name: bpf-maps
          hostPath:
            path: /sys/fs/bpf
            type: DirectoryOrCreate