apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: semamesh-monitor
  namespace: default
  labels:
    release: monitoring
    app: semamesh
spec:
  selector:
    matchLabels:
      app: semamesh
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      interval: 5s
      path: /metrics